spring:
  data:
    #mongodb设置
    mongodb:
      host: localhost
      port: 27017
      database: accounts
      events:
        collection.name: events
        snapshot.collection.name: snapshots
  #Redis配置
  redis:
    port: 6379
    #主机地址
    host: localhost
    pool:
      #连接池最大的活跃连接数，-1表示无限
      max-active: 8
      #连接池最大的空闲连接数，-1表示无限
      max-idle: 8
      #当连接池耗尽时，新获取连接需要等待的最大时间，以毫秒单位，-1表示无限等待
      max-wait: 30
      #连接池中空闲连接的最小数量
      min-idle: 3
    #连接超时时间，毫秒单位
    timeout: 2000

server:
  #端口
  port: 1111
  tomcat:
    #容器编码
    uri-encoding: utf-8
  #开启压缩
  compression:
    enabled: true
    #需要压缩的类型
    mime-types: text/xml,text/plain,text/css,text/javascript,application/xml,application/json,application/javascript
    #最小压缩响应字节数
    min-response-size: 1024

#权限设置
security:
  #基础认证账号密码
  user:
    name: btr
    password: btr
  #oauth2授权
  oauth2:
    #客户端设置
    client:
      clientId: accounts
      clientSecret: accounts
      #token获取Uri
      accessTokenUri: http://localhost:${accounts.port}/oauth/token
      #授权类型 客户端
      grant-type: client_credentials
      #授权范围
      scope: server

feign:
  #开启压缩
  compression:
    enabled: true
    #需要压缩的类型
    mime-types: text/xml,text/plain,text/css,text/javascript,application/xml,application/json,application/javascript
    #最小压缩响应字节数
    min-response-size: 1024
    response.enable: true
  hystrix.enabled: true
  httpclient.enabled: true

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

axon:
  #DistributedCommandBus
  #分布式的CommandBus实现,由多个CommandBus的实例组成,并一起工作来分担负载.
  distributed:
    enabled: true
  amqp:
    exchange: amq.fanout
  eventhandling:
    processors:
      account:
        source: queueMessageSource

---

spring:
  profiles: docker
  data:
    #mongodb设置
    mongodb:
      host: www.borntorain.com
      port: 27017
      database: accounts
      events:
        collection.name: events
        snapshot.collection.name: snapshots
  #Redis配置
  redis:
    port: 6379
    #主机地址
    host: www.borntorain.com
    pool:
      #连接池最大的活跃连接数，-1表示无限
      max-active: 8
      #连接池最大的空闲连接数，-1表示无限
      max-idle: 8
      #当连接池耗尽时，新获取连接需要等待的最大时间，以毫秒单位，-1表示无限等待
      max-wait: 30
      #连接池中空闲连接的最小数量
      min-idle: 3
    #连接超时时间，毫秒单位
    timeout: 2000

server:
  #端口
  port: 1111
  tomcat:
    #容器编码
    uri-encoding: utf-8
  #开启压缩
  compression:
    enabled: true
    #需要压缩的类型
    mime-types: text/xml,text/plain,text/css,text/javascript,application/xml,application/json,application/javascript
    #最小压缩响应字节数
    min-response-size: 1024

#权限设置
security:
  #基础认证账号密码
  user:
    name: admin
    password: admin
  #oauth2授权
  oauth2:
    #客户端设置
    client:
      clientId: accounts
      clientSecret: accounts
      #token获取Uri
      accessTokenUri: https://www.borntorain.com:${accounts.port}/oauth/token
      #授权类型 客户端
      grant-type: client_credentials
      #授权范围
      scope: server

feign:
  #开启压缩
  compression:
    enabled: true
    #需要压缩的类型
    mime-types: text/xml,text/plain,text/css,text/javascript,application/xml,application/json,application/javascript
    #最小压缩响应字节数
    min-response-size: 1024
    response.enable: true
  hystrix.enabled: true
  httpclient.enabled: true

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

axon:
  #DistributedCommandBus
  #分布式的CommandBus实现,由多个CommandBus的实例组成,并一起工作来分担负载.
  distributed:
    enabled: true
  amqp:
    exchange: amq.fanout
  eventhandling:
    processors:
      account:
        source: queueMessageSource
